### ISSUE TITLE
The Tyrell family skips a generation (and is missing Alerie Tyrell)

### ISSUE THREAD

**Issue by Danl2620** [rachelwiles/GoT-Check#1]
```
?- tell_me_about(mace_tyrell).
Status: dead
Parents: [luthor_tyrell,olenna_tyrell]
Children: [loras_tyrell,margaery_tyrell]
Siblings: [loras_tyrell,margaery_tyrell]
true.
```

(Olenna Tyrell is specified as parent of Margaery and Loras when she is actually their grandparent.)

**Comment by rachelwiles** [comment]
Hi, thank you for pointing this out! I've resolved this by amending the Tyrell facts in GoTCheck.pl
